/*
 * generated by Xtext 2.13.0
 */
package br.org.cursomde.ide

import br.org.cursomde.MathRuntimeModule
import br.org.cursomde.MathStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MathIdeSetup extends MathStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MathRuntimeModule, new MathIdeModule))
	}
	
}
