/*
 * generated by Xtext 2.13.0
 */
package br.org.cursomde.ui.tests;

import br.org.cursomde.exemplo1.ui.internal.Exemplo1Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Exemplo1Activator.getInstance().getInjector("br.org.cursomde.Math");
	}

}
