/*
 * generated by Xtext 2.13.0
 */
package br.org.cursomde.ui;

import br.org.cursomde.exemplo1.ui.internal.Exemplo1Activator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MathExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Exemplo1Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Exemplo1Activator activator = Exemplo1Activator.getInstance();
		return activator != null ? activator.getInjector(Exemplo1Activator.BR_ORG_CURSOMDE_MATH) : null;
	}

}
