/*
 * generated by Xtext 2.13.0
 */
package br.org.cursomde


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MathRuntimeModule extends AbstractMathRuntimeModule {
}
