/**
 * generated by Xtext 2.13.0
 */
package br.org.cursomde.math;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expressao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.org.cursomde.math.Expressao#getTermo <em>Termo</em>}</li>
 * </ul>
 *
 * @see br.org.cursomde.math.MathPackage#getExpressao()
 * @model
 * @generated
 */
public interface Expressao extends EObject
{
  /**
   * Returns the value of the '<em><b>Termo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Termo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Termo</em>' attribute.
   * @see #setTermo(int)
   * @see br.org.cursomde.math.MathPackage#getExpressao_Termo()
   * @model
   * @generated
   */
  int getTermo();

  /**
   * Sets the value of the '{@link br.org.cursomde.math.Expressao#getTermo <em>Termo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Termo</em>' attribute.
   * @see #getTermo()
   * @generated
   */
  void setTermo(int value);

} // Expressao
