/**
 * generated by Xtext 2.13.0
 */
package br.org.cursomde.math;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see br.org.cursomde.math.MathFactory
 * @model kind="package"
 * @generated
 */
public interface MathPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "math";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.org.br/cursomde/Math";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "math";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MathPackage eINSTANCE = br.org.cursomde.math.impl.MathPackageImpl.init();

  /**
   * The meta object id for the '{@link br.org.cursomde.math.impl.ProblemaImpl <em>Problema</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.org.cursomde.math.impl.ProblemaImpl
   * @see br.org.cursomde.math.impl.MathPackageImpl#getProblema()
   * @generated
   */
  int PROBLEMA = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEMA__NAME = 0;

  /**
   * The feature id for the '<em><b>Expressoes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEMA__EXPRESSOES = 1;

  /**
   * The number of structural features of the '<em>Problema</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROBLEMA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.org.cursomde.math.impl.ExpressaoImpl <em>Expressao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.org.cursomde.math.impl.ExpressaoImpl
   * @see br.org.cursomde.math.impl.MathPackageImpl#getExpressao()
   * @generated
   */
  int EXPRESSAO = 1;

  /**
   * The feature id for the '<em><b>Termo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO__TERMO = 0;

  /**
   * The number of structural features of the '<em>Expressao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.org.cursomde.math.impl.ArmazenaImpl <em>Armazena</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.org.cursomde.math.impl.ArmazenaImpl
   * @see br.org.cursomde.math.impl.MathPackageImpl#getArmazena()
   * @generated
   */
  int ARMAZENA = 2;

  /**
   * The feature id for the '<em><b>Termo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARMAZENA__TERMO = EXPRESSAO__TERMO;

  /**
   * The number of structural features of the '<em>Armazena</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARMAZENA_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link br.org.cursomde.math.impl.OperacaoImpl <em>Operacao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.org.cursomde.math.impl.OperacaoImpl
   * @see br.org.cursomde.math.impl.MathPackageImpl#getOperacao()
   * @generated
   */
  int OPERACAO = 3;

  /**
   * The feature id for the '<em><b>Termo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERACAO__TERMO = EXPRESSAO__TERMO;

  /**
   * The feature id for the '<em><b>Sinal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERACAO__SINAL = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Operacao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERACAO_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.org.cursomde.math.SinalMatematico <em>Sinal Matematico</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.org.cursomde.math.SinalMatematico
   * @see br.org.cursomde.math.impl.MathPackageImpl#getSinalMatematico()
   * @generated
   */
  int SINAL_MATEMATICO = 4;


  /**
   * Returns the meta object for class '{@link br.org.cursomde.math.Problema <em>Problema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Problema</em>'.
   * @see br.org.cursomde.math.Problema
   * @generated
   */
  EClass getProblema();

  /**
   * Returns the meta object for the attribute '{@link br.org.cursomde.math.Problema#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.org.cursomde.math.Problema#getName()
   * @see #getProblema()
   * @generated
   */
  EAttribute getProblema_Name();

  /**
   * Returns the meta object for the containment reference list '{@link br.org.cursomde.math.Problema#getExpressoes <em>Expressoes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressoes</em>'.
   * @see br.org.cursomde.math.Problema#getExpressoes()
   * @see #getProblema()
   * @generated
   */
  EReference getProblema_Expressoes();

  /**
   * Returns the meta object for class '{@link br.org.cursomde.math.Expressao <em>Expressao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expressao</em>'.
   * @see br.org.cursomde.math.Expressao
   * @generated
   */
  EClass getExpressao();

  /**
   * Returns the meta object for the attribute '{@link br.org.cursomde.math.Expressao#getTermo <em>Termo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Termo</em>'.
   * @see br.org.cursomde.math.Expressao#getTermo()
   * @see #getExpressao()
   * @generated
   */
  EAttribute getExpressao_Termo();

  /**
   * Returns the meta object for class '{@link br.org.cursomde.math.Armazena <em>Armazena</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Armazena</em>'.
   * @see br.org.cursomde.math.Armazena
   * @generated
   */
  EClass getArmazena();

  /**
   * Returns the meta object for class '{@link br.org.cursomde.math.Operacao <em>Operacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operacao</em>'.
   * @see br.org.cursomde.math.Operacao
   * @generated
   */
  EClass getOperacao();

  /**
   * Returns the meta object for the attribute '{@link br.org.cursomde.math.Operacao#getSinal <em>Sinal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sinal</em>'.
   * @see br.org.cursomde.math.Operacao#getSinal()
   * @see #getOperacao()
   * @generated
   */
  EAttribute getOperacao_Sinal();

  /**
   * Returns the meta object for enum '{@link br.org.cursomde.math.SinalMatematico <em>Sinal Matematico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Sinal Matematico</em>'.
   * @see br.org.cursomde.math.SinalMatematico
   * @generated
   */
  EEnum getSinalMatematico();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MathFactory getMathFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link br.org.cursomde.math.impl.ProblemaImpl <em>Problema</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.org.cursomde.math.impl.ProblemaImpl
     * @see br.org.cursomde.math.impl.MathPackageImpl#getProblema()
     * @generated
     */
    EClass PROBLEMA = eINSTANCE.getProblema();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROBLEMA__NAME = eINSTANCE.getProblema_Name();

    /**
     * The meta object literal for the '<em><b>Expressoes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROBLEMA__EXPRESSOES = eINSTANCE.getProblema_Expressoes();

    /**
     * The meta object literal for the '{@link br.org.cursomde.math.impl.ExpressaoImpl <em>Expressao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.org.cursomde.math.impl.ExpressaoImpl
     * @see br.org.cursomde.math.impl.MathPackageImpl#getExpressao()
     * @generated
     */
    EClass EXPRESSAO = eINSTANCE.getExpressao();

    /**
     * The meta object literal for the '<em><b>Termo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSAO__TERMO = eINSTANCE.getExpressao_Termo();

    /**
     * The meta object literal for the '{@link br.org.cursomde.math.impl.ArmazenaImpl <em>Armazena</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.org.cursomde.math.impl.ArmazenaImpl
     * @see br.org.cursomde.math.impl.MathPackageImpl#getArmazena()
     * @generated
     */
    EClass ARMAZENA = eINSTANCE.getArmazena();

    /**
     * The meta object literal for the '{@link br.org.cursomde.math.impl.OperacaoImpl <em>Operacao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.org.cursomde.math.impl.OperacaoImpl
     * @see br.org.cursomde.math.impl.MathPackageImpl#getOperacao()
     * @generated
     */
    EClass OPERACAO = eINSTANCE.getOperacao();

    /**
     * The meta object literal for the '<em><b>Sinal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERACAO__SINAL = eINSTANCE.getOperacao_Sinal();

    /**
     * The meta object literal for the '{@link br.org.cursomde.math.SinalMatematico <em>Sinal Matematico</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.org.cursomde.math.SinalMatematico
     * @see br.org.cursomde.math.impl.MathPackageImpl#getSinalMatematico()
     * @generated
     */
    EEnum SINAL_MATEMATICO = eINSTANCE.getSinalMatematico();

  }

} //MathPackage
