/**
 * generated by Xtext 2.13.0
 */
package br.org.cursomde.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operacao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.org.cursomde.math.Operacao#getSinal <em>Sinal</em>}</li>
 * </ul>
 *
 * @see br.org.cursomde.math.MathPackage#getOperacao()
 * @model
 * @generated
 */
public interface Operacao extends Expressao
{
  /**
   * Returns the value of the '<em><b>Sinal</b></em>' attribute.
   * The literals are from the enumeration {@link br.org.cursomde.math.SinalMatematico}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sinal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sinal</em>' attribute.
   * @see br.org.cursomde.math.SinalMatematico
   * @see #setSinal(SinalMatematico)
   * @see br.org.cursomde.math.MathPackage#getOperacao_Sinal()
   * @model
   * @generated
   */
  SinalMatematico getSinal();

  /**
   * Sets the value of the '{@link br.org.cursomde.math.Operacao#getSinal <em>Sinal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sinal</em>' attribute.
   * @see br.org.cursomde.math.SinalMatematico
   * @see #getSinal()
   * @generated
   */
  void setSinal(SinalMatematico value);

} // Operacao
