/**
 * generated by Xtext 2.13.0
 */
package br.org.cursomde.math;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Problema</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.org.cursomde.math.Problema#getName <em>Name</em>}</li>
 *   <li>{@link br.org.cursomde.math.Problema#getExpressoes <em>Expressoes</em>}</li>
 * </ul>
 *
 * @see br.org.cursomde.math.MathPackage#getProblema()
 * @model
 * @generated
 */
public interface Problema extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.org.cursomde.math.MathPackage#getProblema_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.org.cursomde.math.Problema#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Expressoes</b></em>' containment reference list.
   * The list contents are of type {@link br.org.cursomde.math.Expressao}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressoes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressoes</em>' containment reference list.
   * @see br.org.cursomde.math.MathPackage#getProblema_Expressoes()
   * @model containment="true"
   * @generated
   */
  EList<Expressao> getExpressoes();

} // Problema
