/*
 * generated by Xtext 2.13.0
 */
package br.org.cursomde.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathScopeProvider extends DelegatingScopeProvider {
}
