/**
 * generated by Xtext 2.13.0
 */
package br.org.cursomde.math.impl;

import br.org.cursomde.math.Armazena;
import br.org.cursomde.math.MathPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Armazena</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ArmazenaImpl extends ExpressaoImpl implements Armazena
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ArmazenaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathPackage.Literals.ARMAZENA;
  }

} //ArmazenaImpl
